name: 03 - workflow Runners

on:
 push:

jobs:
   ubuntu-echo:
      runs-on: ubuntu-latest
      steps:
        - name: Show OS
          run: | 
            echo "This job is runnin on an Ubuntu runner"
            echo "Runner OS: $RUNNER_OS"

   windos-echo:
       runs-on: window-latest
       steps:
        - name: "Show OS"
          shell: bash
          run: | 
            echo "This job is runnin on an Ubuntu runner"
            echo "Runner OS: $RUNNER_OS" 
    
     